(add-hook 'ruby-mode-hook 'markers-hl)
(add-hook 'clojure-mode-hook 'markers-hl)
(add-hook 'coffee-mode-hook 'markers-hl)
(add-hook 'css-mode-hook 'markers-hl)
(add-hook 'erlang-mode-hook 'markers-hl)
(add-hook 'espresso-mode-hook 'markers-hl)
(add-hook 'haml-mode-hook 'markers-hl)
(add-hook 'haskell-mode-hook 'markers-hl)
(add-hook 'js2-mode-hook 'markers-hl)
(add-hook 'lua-mode-hook 'markers-hl)
(add-hook 'objj-mode-hook 'markers-hl)
(add-hook 'php-mode-hook 'markers-hl)
(add-hook 'rhtml-mode-hook 'markers-hl)
(add-hook 'sass-mode-hook 'markers-hl)


